plugins { id 'com.android.application' }

def ks = System.getenv("KEYSTORE_FILE")

android {
    namespace 'com.magdi.examencivique'
    compileSdk 36

    defaultConfig {
        applicationId 'com.magdi.examencivique'   // permanent once published on Google Play
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        release {
            if (ks) {
                storeFile file(ks)
                storePassword System.getenv("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (ks) signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.10.1'
}
